# Generated by Django 4.0.3 on 2022-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_defined_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='advance_booking',
            field=models.IntegerField(default=3),
        ),
    ]
