# Generated by Django 4.0.3 on 2022-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_advance_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='defined_check_in_time',
            field=models.TimeField(max_length=4),
        ),
        migrations.AlterField(
            model_name='room',
            name='defined_check_out_time',
            field=models.TimeField(max_length=4),
        ),
    ]
