# Generated by Django 4.0.3 on 2022-04-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
