# Generated by Django 4.0.3 on 2022-04-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_options_alter_room_name_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_booked',
            new_name='booked',
        ),
    ]
